# Generated by Django 5.0.1 on 2024-01-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
