# Generated by Django 5.0.1 on 2024-02-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "blogger",
            "0003_tag_post_comments_post_likes_post_short_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reading_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
