# Generated by Django 5.0.1 on 2024-02-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogger", "0004_post_reading_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name_plural": "tags"},
        ),
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="shares",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
